spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/realworld
    username: postgres
    password: postgres
  jackson:
    deserialization.UNWRAP_ROOT_VALUE: true
    serialization:
      WRAP_ROOT_VALUE: false
      WRITE_DATES_AS_TIMESTAMPS: false

